### ISSUE TITLE
Is it possible to personalize individual icons of photo editing modes?

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#14]
Is it possible to personalize individual icons of photo editing modes?

![88582344-499B-4D06-B5A2-D1327D9CA890](https://user-images.githubusercontent.com/4959534/85230509-f90b1f00-b3f0-11ea-899f-b469b65da927.jpeg)
![5D3A53A8-EC8E-496D-8927-5907D778E3DF](https://user-images.githubusercontent.com/4959534/85230510-fa3c4c00-b3f0-11ea-9933-6203a71c2fe6.jpeg)

**Comment by joshbernfeld** [comment]
This can be done. We will put together an example.

**Comment by joshbernfeld** [comment]
Please ensure you are on the latest version of PixelSDK by running `pod update`.

This can be achieved by subclassing the filter you want to modify, for example:
```swift
class SessionFilterSaturationCustom: SessionFilterSaturation {
    public required init() {
        super.init()
        
        self.common()
    }
    
    public required init(from decoder: Decoder) throws {
        try super.init(from: decoder)
        
        self.common()
    }
    
    func common() {
        self.adjustThumbnailImage = UIImage(named: "thumbnail_example.png")!
    }
}
```

You must then also specify your custom filter in the list of available adjustment filters:
```swift
PixelSDK.shared.adjustmentFilters = [
    SessionFilterBrightness(),
    SessionFilterVibrance(),
    SessionFilterSaturationCustom(), // Your custom saturation filter
    SessionFilterContrast(),
    SessionFilterExposure(),
    SessionFilterHue(),
    SessionFilterWarmth(),
    SessionFilterSharpness(),
    SessionFilterGamma(),
    SessionFilterHighlights(),
    SessionFilterShadows(),
    SessionFilterVignette()
]
```
Note: Since you are manually setting the list of adjustment filters, when new adjustment filters are added in the future you will have to add them to your list in order for them to appear in your app.
