### ISSUE TITLE
Can I change the intensity of individual editing modes?

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#19]
Can I change the intensity of individual editing modes?

Sometimes when editing, when I want to increase (for example) the saturation, I get the impression that even at the maximum setting the saturation is too weak

**Comment by joshbernfeld** [comment]
This can be done. We will put together an example.

**Comment by joshbernfeld** [comment]
Please ensure you are on the latest version of PixelSDK by running `pod update`.

This can be achieved by subclassing the filter you want to modify, for example:
```swift
class SessionFilterSaturationCustom: SessionFilterSaturation {
    public required init() {
        super.init()
        
        self.common()
    }
    
    public required init(from decoder: Decoder) throws {
        try super.init(from: decoder)
        
        self.common()
    }
    
    func common() {
        self.actualIntensityRange = (0, 4)
    }
}
```
Keep in mind the actual intensity ranges for each filter often require different values. For instance the Saturation filter normally has an actual intensity range of [(0, 2.3)](https://www.pixelsdk.com/docs/latest/Classes/SessionFilterSaturation.html#/s:8PixelSDK23SessionFilterSaturationC20actualIntensityRangeSd_Sdtvp) but the Warmth filter has an actual intensity range of [(3000, 11000)](https://www.pixelsdk.com/docs/latest/Classes/SessionFilterWarmth.html#/s:8PixelSDK19SessionFilterWarmthC20actualIntensityRangeSd_Sdtvp). So you will need to check the what the existing value is for the filter before you modify it.

You must then also specify your custom filter in the list of available adjustment filters:
```swift
PixelSDK.shared.adjustmentFilters = [
    SessionFilterBrightness(),
    SessionFilterVibrance(),
    SessionFilterSaturationCustom(), // Your custom saturation filter
    SessionFilterContrast(),
    SessionFilterExposure(),
    SessionFilterHue(),
    SessionFilterWarmth(),
    SessionFilterSharpness(),
    SessionFilterGamma(),
    SessionFilterHighlights(),
    SessionFilterShadows(),
    SessionFilterVignette()
]
```
Note: Since you are manually setting the list of adjustment filters, when new adjustment filters are added in the future you will have to add them to your list in order for them to appear in your app.
