### ISSUE TITLE
I have the impression that the brightness setting works more like fading

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#21]
brightness setting in another application:

![IMG_3655](https://user-images.githubusercontent.com/4959534/85803351-39e39a80-b747-11ea-94a7-7d47e3e54cbf.PNG)

brightness setting in pixelsdk:

![IMG_3656](https://user-images.githubusercontent.com/4959534/85803379-4e279780-b747-11ea-8d50-fe91b49c4e67.PNG)

**Comment by joshbernfeld** [comment]
Can you attach the original image without the brightness filter?

Regards,

Josh

**Comment by janczakb** [comment]
original photo (although in this picture you can not see it well - I tested several photos and I have the impression that pixel sdk causes photo fading than lightening):

![demo](https://user-images.githubusercontent.com/4959534/85804078-0275ed80-b749-11ea-9d43-e71f5ea6cb09.png)

**Comment by joshbernfeld** [comment]
Brightness can be a challenging issue. The problem comes down to whether or not we want to brighten areas that do not already have enough information.

The above brightness filter is likely more of a mixture between vibrance and brightness. Standard brightness filters usually uniformly raise or lower RGB values. In order to get the effect of the above brightness filter, we would have to pick brightness intensity levels for various colors within the image. That or create some kind of intelligent brightness filter. We may want to do this in future.

For the time being, you can always create your own adjustment filter that is a composite of different operations e.g. Brightness and Vibrance, or just use a LookupImage and apply brightness to the lookup image in the photo editor of your choosing.
