### ISSUE TITLE
EditController missing aspectRatio 

### ISSUE THREAD

**Issue by kamirana4** [GottaYotta/PixelSDK#29]
### What are the steps to reproduce?

`EditController` missing the `aspectRatio`

### What did you expect to happen?

I have a case where i use Native `UIImagePickerController` to select the `image` and i just want to use the `EditController` for the editing but i want the image selected previously to have a specific `aspectRatio` same as we can set for `ContainerController`. 

### What happened instead?

I can not find the `aspectRatio` on `EditController` so is there is way i am missing? I couldn't find the documentation for that.

**Comment by joshbernfeld** [comment]
Great question.

The ContainerController normally uses the provided aspectRatio to calculate a cropRect for the Session of the EditController.

Since you are manually creating a Session, you will need to set this cropRect yourself.

The following example will present the EditController with an aspectRatio of your choosing:

```swift
@IBAction func editControllerWithCustomImageSession() {
    let image = UIImage(named: "test_image")!
    
    let session = Session(image: image)
    
    // Set your aspect ratio here
    let aspectRatio = CGSize(width: 1, height: 1)
    
    // Determine the size of the cropRect by scaling the aspectRatio to fit into the image
    let minRatio = min(session.image!.actualSize.width / aspectRatio.width, session.image!.actualSize.height / aspectRatio.height)
    let cropSize = CGSize(width: aspectRatio.width * minRatio, height: aspectRatio.height * minRatio)
    
    // Create the cropRect with our cropSize and also center it in the image
    let cropRect = CGRect(x: session.image!.actualSize.width/2-cropSize.width/2, y: session.image!.actualSize.height/2-cropSize.height/2, width: cropSize.width, height: cropSize.height)
    
    // Set the cropRect on the image
    session.image!.cropRect = cropRect
    
    // Initialize the EditController
    let editController = EditController(session: session)
    editController.delegate = self
    
    // Present the EditController
    let nav = UINavigationController(rootViewController: editController)
    nav.modalPresentationStyle = .fullScreen
    self.present(nav, animated: true, completion: nil)
}
```

If your aspect ratio is portrait (e.g. `CGSize(width: 3, height: 4)`), you may also want to consider setting `editController.compactControls = true` before you present the EditController. This will reduce the height of the editor controls and increase the height of the media preview for an improved user experience.

If you have any more questions, we are happy to help.
