### ISSUE TITLE
Unable to export image

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#6]
What is the reason ?

<ImageExporterError: errorDescription = Internal error: <ImageExporterInternalError: errorDescription = Unable to create a deep copy of session: missingFile(<PixelSDK.Session: 0x281b46500>, "sessionFolder")>.>

**Comment by joshbernfeld** [comment]
Could you attach steps with code that will allow us to reproduce the issue?

If the issue is with a specific image, please also include the original image here in a zip file.

**Comment by janczakb** [comment]
Unfortunately, it still doesn't work.

Sample project: https://we.tl/t-XU1CQEa56m

**Comment by joshbernfeld** [comment]
We are working on a solution and will get back to you shortly.

**Comment by joshbernfeld** [comment]
This has been fixed in the latest release available now.

To apply to your project run the following command:
```
# pod update
```
Then to verify you are on the latest version, open your Podfile.lock file with TextEdit and the version listed for PixelSDK should be 5.4.0.

I have also reattached your sample project with the update pod: https://we.tl/t-5fhyhKZZlU

**Comment by janczakb** [comment]
@joshbernfeld now works correctly
