### ISSUE TITLE
There is still a problem with the export in CameraController

### ISSUE THREAD

**Issue by janczakb** [GottaYotta/PixelSDK#9]
when I use the camera controller and try to save the original photo without filters
Code example: 

```
func cameraController(_ cameraController: CameraController, didFinishWithSession session: Session) {

        if let image = session.image {
            ImageExporter.shared.export(image: image, completion: { (error, uiImage) in
                    if let error = error {
                        print("Unable to export image: \(error)")
                        return
                    }
                print("done")
            })
        }
    }
```
Error: 
`Unable to export image: <ImageExporterError: errorDescription = Internal error: <ImageExporterInternalError: errorDescription = Unable to create a deep copy of session: emptyVar(<PixelSDK.SessionImage: 0x283415ba0>, "naturalSize")>.>`

**Comment by joshbernfeld** [comment]
This bug has been fixed in the latest release (6.0.0). Please run `pod update`.

Note: The ContainerControllerDelegate function
`func containerController(_ containerController: ContainerController, didChangeMode mode: ContainerMode)`

Has been renamed to:
`func containerControllerDidChangeMode(_ containerController: ContainerController)`
